/*
*  Copyright (c) 2015 Samsung Electronics Co., Ltd All Rights Reserved 
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*  http://www.apache.org/licenses/LICENSE-2.0
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*/

#ifndef __VOICE_CONTROL_PANEL_COMMAND_H
#define __VOICE_CONTROL_PANEL_COMMAND_H

#ifdef __cplusplus
extern "C" {
#endif

#if 0
#define	NUM_COMMAND_DEPTH	2
#endif

#define NUM_COMMAND_1ST		12
#if 0
#define NUM_COMMAND_2ND		8
#endif

#define MAX_VOICE_LIST		1000
#define MAX_VOICE_LENGTH	30

typedef struct Voice_command {
    char voice[MAX_VOICE_LENGTH + 1];
    int command_id;
} voice_command_h;

extern char* g_command_1st[NUM_COMMAND_1ST];

extern voice_command_h voice_command_list_kr[MAX_VOICE_LIST + 1];
extern voice_command_h voice_command_list_en[MAX_VOICE_LIST + 1];

#if 0
extern char* g_command_2nd[NUM_COMMAND_1ST][NUM_COMMAND_2ND];

extern char* g_hint_1st[NUM_COMMAND_1ST];
extern char* g_hint_2nd[NUM_COMMAND_1ST][NUM_COMMAND_2ND];
#endif

typedef enum {
	CMD_ERROR_UNKNOWN   = -6,
	CMD_ERROR_UNKNOWN_5 = -5,
	CMD_ERROR_UNKNOWN_4 = -4,
	CMD_ERROR_UNKNOWN_3 = -3,
	CMD_ERROR_UNKNOWN_2 = -2,
	CMD_ERROR_UNKNOWN_1 = -1,
	CMD_ERROR_RECOGNITION = 0,

	CMD_STOP,
	CMD_PAUSE,
	CMD_START,
	CMD_RESTART,
	CMD_AGAIN,

	CMD_OK,
	CMD_CANCLE,

	CMD_POWER_ON,
	CMD_POWER_OFF,

	CMD_MSG_MODE_IMPERIAL,
	CMD_MSG_MODE_SHOULDER,
	CMD_MSG_MODE_WAIST,
	CMD_MSG_MODE_KNEE,
	CMD_MSG_MODE_MANUAL,
	CMD_MSG_MODE_USER1,
	CMD_MSG_MODE_USER2,
	CMD_MSG_MODE_USER3,

	CMD_UI_FAVORITE,
	CMD_UI_SETTING,
	CMD_UI_SETTING_MAINPAGE,
	CMD_UI_SETTING_WIFI,
	CMD_UI_SETTING_BT,

	CMD_UI_PAGE_DOWN,
	CMD_UI_PAGE_UP,
	CMD_UI_PAGE_BOTTOM,
	CMD_UI_PAGE_TOP,

	CMD_CHAIR_ANGLE_ZEROGRAVITY,
	CMD_CHAIR_ANGLE_INIT,
	CMD_CHAIR_ANGLE_SLEEP,

	CMD_MSG_TIME_DOWN,
	CMD_MSG_TIME_UP,

	CMD_MSG_STRENGTH_DOWN,
	CMD_MSG_STRENGTH_UP,

	CMD_CHAIR_ALLHEATER_ON_OFF,
	CMD_CHAIR_ALLHEATER_ON,
	CMD_CHAIR_ALLHEATER_OFF,
	CMD_CHAIR_LEGHEATER_ON_OFF,
	CMD_CHAIR_LEGHEATER_ON,
	CMD_CHAIR_LEGHEATER_OFF,
	CMD_CHAIR_BACKHEATER_ON_OFF,
	CMD_CHAIR_BACKHEATER_ON,
	CMD_CHAIR_BACKHEATER_OFF,
	CMD_CHAIR_FOOTROLLER_ON_OFF,
	CMD_CHAIR_FOOTROLLER_ON,
	CMD_CHAIR_FOOTROLLER_OFF,

	CMD_MUSIC_PLAY,
	CMD_MUSIC_STOP,
	CMD_MUSIC_PAUSE,
	CMD_MUSIC_PREV,
	CMD_MUSIC_NEXT,

	CMD_VOLUME_DOWN,
	CMD_VOLUME_UP,
	CMD_VOLUME_ON_MUTE,
	CMD_VOLUME_ON,
	CMD_VOLUME_MUTE,

	CMD_LOCAL_MUSIC_PLAY,
	CMD_LOCAL_MUSIC_STOP,
	CMD_LOCAL_MUSIC_PAUSE,
	CMD_LOCAL_MUSIC_PREV,
	CMD_LOCAL_MUSIC_NEXT,

	CMD_SPEAKER_VOLUME_DOWN,
	CMD_SPEAKER_VOLUME_UP,
	CMD_SPEAKER_VOLUME_ON_MUTE,
	CMD_SPEAKER_VOLUME_ON,
	CMD_SPEAKER_VOLUME_MUTE,

	CMD_BT_SETTING,
	CMD_BT_CONNECT,
	CMD_BT_CONNECT_DEVICE1,
	CMD_BT_CONNECT_DEVICE2,
	CMD_BT_CONNECT_DEVICE3,
	CMD_BT_CONNECT_OFF,

	CMD_BT_MUSIC_PLAY,
	CMD_BT_MUSIC_STOP,
	CMD_BT_MUSIC_PAUSE,
	CMD_BT_MUSIC_PREV,
	CMD_BT_MUSIC_NEXT,

	CMD_BT_VOLUME_DOWN,
	CMD_BT_VOLUME_UP,
	CMD_BT_VOLUME_ON_MUTE,
	CMD_BT_VOLUME_ON,
	CMD_BT_VOLUME_MUTE,

	CMD_UI_TV_REMOCON_VIEW_HIDE,
	CMD_UI_TV_REMOCON_VIEW,
	CMD_UI_TV_REMOCON_HIDE,

	CMD_TV_POWER_ON_OFF,
	CMD_TV_POWER_ON,
	CMD_TV_POWER_OFF,
	CMD_TV_KEYBOARD_CONNECT,
	CMD_TV_KEYBOARD_CONNECT_OFF,
	CMD_TV_KEYBOARD_ENTER,
	CMD_TV_KEYBOARD_ESC,
	CMD_TV_KEYBOARD_UP,
	CMD_TV_KEYBOARD_DOWN,
	CMD_TV_KEYBOARD_LEFT,
	CMD_TV_KEYBOARD_RIGHT,
	CMD_TV_KEYBOARD_SMARTKEY,
	CMD_TV_SPEAKER_CONNECT,
	CMD_TV_SPEAKER_CONNECT_OFF,
	CMD_TV_VOLUME_DOWN,
	CMD_TV_VOLUME_UP,
	CMD_TV_VOLUME_ON_MUTE,
	CMD_TV_VOLUME_ON,
	CMD_TV_VOLUME_MUTE,
	CMD_TV_CHANNEL_DOWN,
	CMD_TV_CHANNEL_UP,

	CMD_NONE,
	CMD_LIST_END
} command_type_e;

#ifdef __cplusplus
}
#endif

#endif /* __VOICE_CONTROL_PANEL_VIEW_H */

/*
vi:ts=4:ai:nowrap:expandtab
*/
